### ISSUE TITLE
Twitch Client Update!

### ISSUE THREAD

**Issue by Jaia93tv** [jahraphael/raiderio-addon#20]
Hi there I have an issue when I am trying to update thro Twitch Client either it takes more than an hour to update or it don't even want to start. If you guys know what is the problem with it I can update all other addons without any issues but not Raider.io. Usually I need to delete and install again the addon it self so it will be up to date.
Thanks..

**Comment by jahraphael** [comment]
Hi there - apologies for the delayed response. I'm unsure what the cause here would be, aside from potentially just size of our addon.  Our addon encodes a lot of data directly into it, since the WoW API cannot directly talk to external servers.  Because of this, the size of the addon is large - and perhaps this size is the primary problem.

Unfortunately there's not much we can advise on this front right now.  Eventually when we have our own updater client, it will be able to more optimally decide what data to synchronize, which should reduce the bandwidth requirements.
