### ISSUE TITLE
Massive frame rate lag when mousing over UI elements

### ISSUE THREAD

**Issue by Mrhgb** [jahraphael/raiderio-addon#21]
I've made a video showing the issue, with your addon enabled I get massive frame rate lag when mousing over UI elements, but it's perfect with it disabled. You can see the frame rate fluctuate wildly in the bottom right, and it just chops up completely.

https://streamable.com/bpn5f

**Comment by Vladinator89** [comment]
Hello Mrhgb!

The reason for it is simple; because the addon modules that contain the actual data for the players is so big, each time you mouse anything on the UI that shows performance information like CPU/RAM statistics, it will lag you as the game is checking the size of the loaded data, and it's around 50 MB per faction in EU and it will do a full re-check each time you mouse over those UI elements.

It happens to me as well, and my solution is to avoid accidentally mousing over those UI elements that trigger it. I believe elvUI shows it when you mouse over the computer (that shows latency) in the bottom left on your video, and the FPS/RAM/CPU widget on the bottom right.

**Comment by Mrhgb** [comment]
Ah that's a shame, so there's nothing you can do on your end to minimise it?

**Comment by jahraphael** [comment]
Unfortunately I don't think there is anything we can do here. This is a side effect of how the addon needs to work, since in WoW API there is no way to make requests out to external sites.
